### ISSUE TITLE
Creación de `ResultadoUsoItem` para poder desacoplar Juego

### ISSUE THREAD

**Issue by santiemanuel** [Academia-Cimne-Iber-Developers/java-rpg-ex#4]
# Implementación de ResultadoUsoItem y Mejora del Sistema de Uso de Items

## Descripción
Actualmente, el sistema de uso de items no proporciona una forma clara de manejar y comunicar los diferentes resultados posibles (éxito, item no consumible, item no encontrado) y no tenemos la posibilidad de recuperar el Item utilizado para casos de uso futuro. Implementaremos la clase `ResultadoUsoItem` y modificaremos las clases relacionadas para mejorar el manejo de estos casos y preparar el sistema para futuras expansiones.

## Objetivos
1. Crear la clase `ResultadoUsoItem` para encapsular el resultado del uso de items.
2. Modificar `GestorInventario` para utilizar `ResultadoUsoItem`.
3. Actualizar `Juego` para trabajar con la nueva implementación.
4. Mejorar la comunicación del resultado del uso de items al jugador.

### 1. Implementar la clase `ResultadoUsoItem`
- Crear la clase `ResultadoUsoItem` con los siguientes atributos:
  - `boolean exito`
  - `String mensaje`
  - `Item itemUsado`
- Implementar constructor, getters y cualquier otro método necesario.
- Esto nos permite tener tanto la info como el `Item` si lo necesitamos para algo más.

### 2. Modificar GestorInventario
- Actualizar el método `usarObjeto` para que devuelva un `ResultadoUsoItem`.
- Manejar los diferentes casos (éxito, item no consumible, item no encontrado) creando los `ResultadoUsoItem` apropiados.

### 3. Actualizar Juego
- Modificar el método `usarItem` para que trabaje con `ResultadoUsoItem`.

### 5. Actualizar Interfaz (si se considera necesario)
- Modificar los métodos relacionados con el uso de items para trabajar con la nueva implementación.

## Criterios de Aceptación
1. La clase `ResultadoUsoItem` está implementada correctamente y encapsula toda la información necesaria.
2. `GestorInventario` utiliza `ResultadoUsoItem` para comunicar el resultado de usar un objeto.
3. `Juego` manejan correctamente los `ResultadoUsoItem`.
4. El jugador recibe mensajes claros y apropiados para cada caso de uso de item.
5. El código está preparado para la futura implementación del sistema de misiones.

**Comment by lucasromanh** [comment]
Santi, quisiera trabajar este issue yo  , asi se me lo asigna

**Comment by CamperoFredi** [comment]
Desarrollaremos este issue para la presentacion del Trabajo Practico

**Comment by FerBarroso17** [comment]
Hola Profe con el compañero Matias Suarez vamos a trabajar en ésta issue

**Comment by santiemanuel** [comment]
Bien Fernando.

Aviso que no se aceptan más propuestas a esta issue, ya sumaré nuevas donde podrán trabajar.
