### ISSUE TITLE
Desacoplamiento de acciones en `Juego`

### ISSUE THREAD

**Issue by santiemanuel** [Academia-Cimne-Iber-Developers/java-rpg-ex#5]
# Refactorización de Juego y Adición de Controlador de Acciones

## Descripción
Actualmente, la clase `Juego` maneja directamente todas las acciones del jugador y la lógica del juego. Para mejorar la modularidad y preparar el terreno para futuras expansiones (como el sistema de misiones), necesitamos refactorizar la clase `Juego` y crear una nueva clase `ControladorAcciones` que maneje las acciones del jugador.

## Objetivos
1. Crear una nueva clase `ControladorAcciones` que maneje las acciones del jugador.
2. Refactorizar la clase `Juego` para trabajar con el nuevo `ControladorAcciones`.
3. Modificar los métodos en `Juego` para que devuelvan los objetos relevantes después de cada acción.
4. Preparar la estructura para la futura implementación del sistema de misiones.

### 1. Crear la clase ControladorAcciones
- Crear una nueva clase `ControladorAcciones`.
- Implementar un método `procesarAccion(String opcion)` que maneje las diferentes acciones del jugador.

### 2. Refactorizar la clase Juego
- Modificar el constructor de `Juego` para inicializar y usar `ControladorAcciones`.
- Actualizar el método `iniciar()` para usar `ControladorAcciones`.
- Modificar los métodos existentes para que devuelvan objetos relevantes:
  - `explorarUbicacion()`: Devolver la nueva `Ubicacion`.
  - `luchar()`: Devolver un `boolean` indicando victoria o derrota.
  - Mantener `usarItem(String nombreItem)` sin cambios en su funcionamiento actual. Luego de aplicar la issue #4 

### 3. Actualizar la interfaz de usuario
- Modificar la clase `Interfaz` para trabajar con el nuevo `ControladorAcciones` si es necesario.

## Ejemplo de Implementación

```java
// ControladorAcciones.java
public class ControladorAcciones {
    private Juego juego;

    public ControladorAcciones(Juego juego) {
        this.juego = juego;
    }

    public void procesarAccion(String opcion) {
        switch (opcion) {
            case "e":
                Ubicacion nuevaUbicacion = juego.explorarUbicacion();
                // Aquí procesaríamos el evento de movimiento en el futuro
                break;
            case "l":
                Enemigo enemigo = juego.getJugador().getUbicacionActual().getEnemigoActual();
                if (enemigo != null) {
                    boolean victoria = juego.luchar(enemigo);
                    // Aquí procesaríamos el evento de combate en el futuro
                }
                break;
            // ... otros casos
        }
    }
}

// Juego.java (boceto de modificaciones)
public class Juego {
    private ControladorAcciones controladorAcciones;
    private GestorInventario gestorInventario;
    // ... otros atributos

    public Juego() {
        // ... otras inicializaciones
        this.controladorAcciones = new ControladorAcciones(this);
        this.gestorInventario = new GestorInventario();
    }

    public void iniciar() {
        while (true) {
            interfaz.actualizarPantalla();
            String opcion = interfaz.obtenerEntrada();
            controladorAcciones.procesarAccion(opcion);
        }
    }

    public Ubicacion explorarUbicacion() {
        // Lógica para explorar
        Ubicacion nuevaUbicacion = // ... resultado de la lógica de exploración
        return nuevaUbicacion;
    }

    public boolean luchar(Enemigo enemigo) {
        // Lógica de combate
        boolean victoria = // ... lógica de combate
        return victoria;
    }

    public String usarItem(String nombreItem) {
        // Lógica para preguntar el item deseado
        return gestorInventario.usarObjeto(jugador, jugador.getInventario(), nombreItem);
    }

    // ... otros métodos necesarios
}
```

## Criterios de Aceptación
1. La clase `ControladorAcciones` está implementada y maneja correctamente las acciones del jugador.
2. La clase `Juego` está refactorizada para trabajar con `ControladorAcciones`.
3. Los métodos en `Juego` devuelven los objetos relevantes después de cada acción.
4. El flujo del juego sigue funcionando correctamente después de la refactorización.
5. El código está preparado para la futura implementación del sistema de misiones.
6. Se mantiene la funcionalidad existente sin introducir nuevos errores, especialmente en el uso de items.

## Notas Adicionales
- Esta refactorización es un paso preparatorio para la implementación del sistema de misiones.
- Asegurarse de que todos los casos de uso existentes sigan funcionando correctamente después de la refactorización.
- Considerar la posibilidad de que el gestor de combate nos pueda devolver el enemigo en la ubicación actual para evitar el uso de `juego.getJugador().getUbicacionActual().getEnemigoActual()` directamente en el controlador de acciones.

**Comment by DySHITal** [comment]
Hola profe, de esta issue vamos a trabajar Ana Fernandez y yo (Alfredo Moreno).

**Comment by santiemanuel** [comment]
Hola Alfredo, bien

**Comment by JaggoLAP** [comment]
Hola Profe, voy trabajar en esta issue.

**Comment by santiemanuel** [comment]
> Hola Profe, voy trabajar en esta issue. Soy Luis A. Perez

Hola Luis, perfecto. Bien, cierro hasta acá las propuestas de implementación de esta issue.

**Comment by santiemanuel** [comment]
Feature integrada.
